### ISSUE TITLE
Issue with calculating some results

### ISSUE THREAD

**Issue by baan2000** [rawling/wr-calc#3]
Hi there,

I've noticed that it doesn't always calculate Irish results. Also with New Zealand results.

For instance, wen't on this evening, and without changing anything, it had pre-populated the Ireland - USA result in the right hand side (game results) but in the rankings/points on the left, there was no change. Similarly for NZ. I deleted all matches apart from the Ireland one, and still no points change (but all others disappeared as I deleted the matches).  I then re-created the NZ match - no points changes and then the Scotland - Argentina match. Only this last one resulted in any points changes. See attached screenshot of this.
![calc](https://user-images.githubusercontent.com/45321809/48974062-90599600-f045-11e8-8a31-958fbf5f0080.png)

I'm using Win10Pro, Chrome. I experience the same issue on Firefox and MS Edge.  

(I'm really hoping that this is not a user-issue!!)

By the way - great calculator, it's fantastic usually, but I noticed this issue first last week (IE v NZ) and this week, but it definitely used to work before!

**Comment by rawling** [comment]
When a team wins a match, the base ranking increase ranges from +2 (they were 10 points below their opponents) through +1 (they had equal points to their opponents) to +0 (they were 10 points above their opponents). Since NZ and Ire were >10 points above their opponents here, they could gain nothing from the matches.

Last week you should've seen roughly a potential +/-1 change for both NZ and Ire as they are quite close in ranking.

**Comment by baan2000** [comment]
ooooh..... now I just look silly 🤣 

Fair enough, thanks for replying! I'm not sure what I did last week - it was on my phone, to be fair, so may have been an input issue. It was when I went in on the laptop tonight, I thought I'd found an issue. 

sorry about that!!
