### ISSUE TITLE
Simulate match with Italy, ranking changes for Iran

### ISSUE THREAD

**Issue by Atsuga** [rawling/wr-calc#7]
Hi, I was playing with this weekend 6 nations matchs and was surprised not to see raking changes for Italy.
When scrolling down, I saw however a change for Iran.

[https://rawling.github.io/wr-calc/?d=2022-03-14&f=1:64,52;699,753;721,770;33,41,35,12;44,756;36,35,30,25;42,34,32,18;720,43;]

Never saw that previously.

**Comment by rawling** [comment]
Italy's ranking doesn't change because it's too far below Wales already. (>
10pt, even before you include Wales's 3pt for home advantage.)

Iran's ranking change seems to be because they're exactly joint with
another country - the official data gives them the same rank, but my code
forces one of them to drop down a rank
